<?php

function wpts_add_action_plugin( $actions, $plugin_file ) {
	$gp_locale = wpts_get_gp_locale();
	if ($gp_locale) {
		// Only add action if gp_locale exist
		$url = 'https://translate.wordpress.org/locale/' . $gp_locale . '/default/wp-plugins/' . substr($plugin_file, 0, strpos($plugin_file, '/')) ;
		$settings = array('translate' => '<a href="' . $url . '">' . __('TranslateMe', 'wp-translation') . '</a>');
		$actions = array_merge($settings, $actions);
	}
	return $actions;
}

// Create Text Domain For Translations
function wpts_textdomain() {
	load_plugin_textdomain( 'wp-translation', false, dirname( plugin_basename( __FILE__ ) ) );
}

function wpts_get_gp_locale(){
	// Get the list from a central place like https://make.wordpress.org/polyglots/teams/ in a next version
	$conversion_table = array (
		'af' => 'af',
		'ak' => 'ak',
		'sq' => 'sq',
		'arq' => 'arq',
		'am' => 'am',
		'ar' => 'ar',
		'hy' => 'hy',
		'rup_MK' => 'rup',
		'frp' => 'frp',
		'as' => 'as',
		'ast' => 'ast',
		'az' => 'az',
		'az_TR' => 'az-tr',
		'bcc' => 'bcc',
		'ba' => 'ba',
		'eu' => 'eu',
		'bel' => 'bel',
		'bn_BD' => 'bn',
		'bs_BA' => 'bs',
		'bre' => 'br',
		'bg_BG' => 'bg',
		'ca' => 'ca',
		'bal' => 'bal',
		'ceb' => 'ceb',
		'zh_CN' => 'zh-cn',
		'zh_HK' => 'zh-hk',
		'zh_TW' => 'zh-tw',
		'co' => 'co',
		'hr' => 'hr',
		'cs_CZ' => 'cs',
		'da_DK' => 'da',
		'dv' => 'dv',
		'nl_NL' => 'nl',
		'nl_BE' => 'nl-be',
		'dzo' => 'dzo',
		'art_xemoji' => 'art-xemoji',
		'en_AU' => 'en-au',
		'en_CA' => 'en-ca',
		'en_NZ' => 'en-nz',
		'en_ZA' => 'en-za',
		'en_GB' => 'en-gb',
		'eo' => 'eo',
		'et' => 'et',
		'fo' => 'fo',
		'fi' => 'fi',
		'fr_BE' => 'fr-be',
		'fr_CA' => 'fr-ca',
		'fr_FR' => 'fr',
		'fy' => 'fy',
		'fur' => 'fur',
		'fuc' => 'fuc',
		'gl_ES' => 'gl',
		'ka_GE' => 'ka',
		'de_DE' => 'de',
		'de_CH' => 'de-ch',
		'el' => 'el',
		'kal' => 'kal',
		'gn' => 'gn',
		'gu' => 'gu',
		'hat' => 'hat',
		'haw_US' => 'haw',
		'haz' => 'haz',
		'he_IL' => 'he',
		'hi_IN' => 'hi',
		'hu_HU' => 'hu',
		'is_IS' => 'is',
		'ido' => 'ido',
		'id_ID' => 'id',
		'ga' => 'ga',
		'it_IT' => 'it',
		'ja' => 'ja',
		'jv_ID' => 'jv',
		'kab' => 'kab',
		'kn' => 'kn',
		'kk' => 'kk',
		'km' => 'km',
		'kin' => 'kin',
		'ky_KY' => 'ky',
		'ko_KR' => 'ko',
		'ckb' => 'ckb',
		'lo' => 'lo',
		'lv' => 'lv',
		'li' => 'li',
		'lin' => 'lin',
		'lt_LT' => 'lt',
		'lb_LU' => 'lb',
		'mk_MK' => 'mk',
		'mg_MG' => 'mg',
		'ms_MY' => 'ms',
		'ml_IN' => 'ml',
		'mri' => 'mri',
		'mr' => 'mr',
		'xmf' => 'xmf',
		'mn' => 'mn',
		'me_ME' => 'me',
		'ary' => 'ary',
		'my_MM' => 'mya',
		'ne_NP' => 'ne',
		'nb_NO' => 'nb',
		'nn_NO' => 'nn',
		'oci' => 'oci',
		'ory' => 'ory',
		'os' => 'os',
		'ps' => 'ps',
		'fa_IR' => 'fa',
		'fa_AF' => 'fa-af',
		'pl_PL' => 'pl',
		'pt_BR' => 'pt-br',
		'pt_PT' => 'pt',
		'pa_IN' => 'pa',
		'rhg' => 'rhg',
		'ro_RO' => 'ro',
		'roh' => 'roh',
		'ru_RU' => 'ru',
		'rue' => 'rue',
		'sah' => 'sah',
		'sa_IN' => 'sa-in',
		'srd' => 'srd',
		'gd' => 'gd',
		'sr_RS' => 'sr',
		'szl' => 'szl',
		'snd' => 'snd',
		'si_LK' => 'si',
		'sk_SK' => 'sk',
		'sl_SI' => 'sl',
		'so_SO' => 'so',
		'azb' => 'azb',
		'es_AR' => 'es-ar',
		'es_CL' => 'es-cl',
		'es_CO' => 'es-co',
		'es_GT' => 'es-gt',
		'es_MX' => 'es-mx',
		'es_PE' => 'es-pe',
		'es_PR' => 'es-pr',
		'es_ES' => 'es',
		'es_VE' => 'es-ve',
		'su_ID' => 'su',
		'sw' => 'sw',
		'sv_SE' => 'sv',
		'gsw' => 'gsw',
		'tl' => 'tl',
		'tah' => 'tah',
		'tg' => 'tg',
		'tzm' => 'tzm',
		'ta_IN' => 'ta',
		'ta_LK' => 'ta-lk',
		'tt_RU' => 'tt',
		'te' => 'te',
		'th' => 'th',
		'bo' => 'bo',
		'tir' => 'tir',
		'tr_TR' => 'tr',
		'tuk' => 'tuk',
		'twd' => 'twd',
		'ug_CN' => 'ug',
		'uk' => 'uk',
		'ur' => 'ur',
		'uz_UZ' => 'uz',
		'vi' => 'vi',
		'wa' => 'wa',
		'cy' => 'cy',
		'yor' => 'yor',
	);
	$site_locale = get_locale();
	
	return $conversion_table[$site_locale];
}

?>